### PR TITLE
fix(app): fix sidebar

### LINKED ISSUE #462: `QuestionsSidebar` issues
1. Cannot scroll content of the sidebar when it is displayed on mobile in horizonrtal mode:

2. Height of the sidebar does not match to the content of it:

### PR DESCRIPTION
**Pull request by grzegorzpokorski**
This PR fixes #462 issue. Changes:
 - change an aside divider from solution which based on shadows to border with gradient,
 - adjust width of a sidebar, adjust demensions of links and gaps inside lists in each section inner sidebar,
 - add ability to scroll sidebar when it does not fit whole on height of the viewport,

### CODE REVIEW

File: apps/app/src/components/QuestionsSidebar/QuestionsSidebar.tsx [hunk 1]
```diff
@@ -32,7 +38,10 @@ export const QuestionsSidebar = () => {
 			<Button variant="brandingInverse" className="mt-auto sm:hidden" onClick={closeSidebar}>
 				Pokaż wyniki
 			</Button>
-			<CloseButton className="absolute top-1 right-1 sm:hidden" onClick={closeSidebar} />
+			<CloseButton
+				className="absolute top-1 right-1 sm:invisible sm:hidden"
```
Comment (grzegorzpokorski) [inline apps/app/src/components/QuestionsSidebar/QuestionsSidebar.tsx:42]: Remove sm:`invisible`

File: apps/app/src/components/QuestionsSidebar/QuestionsSidebarSection.tsx [hunk 2]
```diff
@@ -6,8 +6,8 @@ type QuestionsSidebarSection = Readonly<{
 }>;
 
 export const QuestionsSidebarSection = ({ title, children }: QuestionsSidebarSection) => (
-	<section className="mt-6">
-		<h2 className="mb-6 border-b border-violet-700 pb-2 text-sm text-violet-700 dark:border-neutral-200 dark:text-neutral-200">
+	<section className="px-1 pb-6 sm:last-of-type:pb-0">
+		<h2 className="mb-6 flex flex-col border-b border-violet-700 pb-2 text-sm text-violet-700 dark:border-neutral-200 dark:text-neutral-200">
```
Comment (grzegorzpokorski) [inline apps/app/src/components/QuestionsSidebar/QuestionsSidebarSection.tsx:10]: Remove `flex flex-col`
